import React, { useState } from "react";

import styles from "./home.module.scss";
import { slugify } from "@/lib/utils";
import Header from "@/components/Header";
import { Search } from "@/components/Search";
import Image from "next/image";
import icon from "./icon.svg";

export default function Home() {
  console.log(icon);

  return (
    <>
      <main className={styles.home}>
        <Image src={icon} alt="Infinipedia" />
        <h1>Welcome to Infinipedia!</h1>
        <p>
          Infinipedia is an AI powered infinite encyclopedia. All content is
          generated by OpenAI's GPT-3 Large Language Model.
        </p>
        <h2>
          Type in <i>any</i> topic to read an article about it:
        </h2>
        <Search />
      </main>
    </>
  );
}
