"use client";

import React, { useState } from "react";

import styles from "./home.module.scss";
import { slugify } from "@/lib/utils";

export default function Home() {
  const [error, setError] = useState<string | null>(null);

  const onSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    const topic = formData.get("topic");
    if (typeof topic === "string" && topic.length > 0) {
      window.location.href = `/wiki/${slugify(topic)}`;
    } else {
      setError("Please enter a topic");
    }
  };

  return (
    <main className={styles.home}>
      <h1>Welcome to Infinipedia!</h1>
      <p>
        Infinipedia is an AI powered infinite encyclopedia. All content is
        generated by OpenAI's GPT-3 Large Language Model.
      </p>
      <h2>
        Type in <i>any</i> topic to read an article about it:
      </h2>
      <form className={styles.form} onSubmit={onSubmit}>
        <input
          className={styles.input}
          type="text"
          name="topic"
          placeholder="Pick a topic, any topic..."
        />
        <button>Go</button>
      </form>
      {error && <p className={styles.error}>{error}</p>}
    </main>
  );
}
